Traceback (most recent call last):
  File "train.py", line 105, in <module>
    train(args)
  File "/Users/a./fast_mri/utils/learning/train_part.py", line 129, in train
    torch.cuda.set_device(device)
  File "/opt/homebrew/anaconda3/envs/fastmri/lib/python3.8/site-packages/torch/cuda/__init__.py", line 324, in set_device
    device = _get_device_index(device)
  File "/opt/homebrew/anaconda3/envs/fastmri/lib/python3.8/site-packages/torch/cuda/_utils.py", line 30, in _get_device_index
    raise ValueError('Expected a cuda device, but got: {}'.format(device))
ValueError: Expected a cuda device, but got: cpu
Namespace(GPU_NUM=0, amp=False, aug=False, batch_size=1, cascade=12, chans=18, collate=False, config='./utils/model/config/swin_36.yaml', data_path_train=PosixPath('/root/Data/train'), data_path_val=PosixPath('/root/Data/val'), edge=False, edge_weight=1, gamma=0.5, grad_accumulation=4, grad_norm=100000000.0, input_key='kspace', loss='ssim', loss_mask=False, lr=0.0003, max_key='max', model='varnet', net_name=PosixPath('test'), num_epochs=30, num_workers=4, report_interval=100, resume_from=None, scheduler=None, seed=2023, sens_chans=8, step_size=5, target_key='image_label', unet='plain')